#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="${CONFIG_FILE:-/etc/robot24/socketcan_boot.conf}"
SERVICE_FILE="${SERVICE_FILE:-/etc/systemd/system/robot24-socketcan.service}"
BITRATE="${BITRATE:-1000000}"
TXQUEUELEN="${TXQUEUELEN:-1000}"
TARGETS=(can0 can1)

usage() {
  cat <<'EOF'
Usage: socketcan_boot_setup.sh <command>

Commands:
  install    Record the current can0/can1 hardware identity and install boot service
  apply      Rename detected adapters back to recorded can0/can1 names, then bring them up
  status     Show recorded identities and current CAN interface state
  uninstall  Disable and remove the boot service and recorded identity file

Notes:
  install must be run while the two adapters are already named as desired.
  The script preserves the current can0/can1 assignment by USB serial/path; it does not
  decide the order from insertion timing at future boots.
EOF
}

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This command must run as root. Try: sudo $0 $*" >&2
    exit 1
  fi
}

udev_prop() {
  local iface="$1"
  local key="$2"
  udevadm info -q property -p "/sys/class/net/${iface}" 2>/dev/null \
    | awk -F= -v key="${key}" '$1 == key {print $2; exit}'
}

iface_identity() {
  local iface="$1"
  local serial path driver
  serial="$(udev_prop "${iface}" ID_SERIAL_SHORT || true)"
  path="$(udev_prop "${iface}" ID_PATH || true)"
  driver="$(udev_prop "${iface}" ID_NET_DRIVER || true)"

  if [[ -n "${serial}" ]]; then
    printf 'serial:%s\n' "${serial}"
  elif [[ -n "${path}" ]]; then
    printf 'path:%s\n' "${path}"
  elif [[ -n "${driver}" ]]; then
    printf 'driver:%s:%s\n' "${driver}" "${iface}"
  else
    return 1
  fi
}

find_iface_by_identity() {
  local identity="$1"
  local iface current

  for sys_iface in /sys/class/net/*; do
    iface="$(basename "${sys_iface}")"
    [[ "${iface}" == can* || "${iface}" == r24_can*_tmp ]] || continue
    current="$(iface_identity "${iface}" 2>/dev/null || true)"
    if [[ "${current}" == "${identity}" ]]; then
      printf '%s\n' "${iface}"
      return 0
    fi
  done

  return 1
}

load_config() {
  if [[ ! -r "${CONFIG_FILE}" ]]; then
    echo "Missing ${CONFIG_FILE}. Run install first." >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"
}

identity_var_name() {
  local target="$1"
  printf '%s_IDENTITY' "${target^^}"
}

record_current_mapping() {
  local target identity

  install -d -m 0755 "$(dirname "${CONFIG_FILE}")"
  umask 022
  {
    echo '# Generated by robot24 socketcan_boot_setup.sh.'
    echo '# Re-run install only when the currently desired can0/can1 hardware assignment changes.'
    printf 'BITRATE=%q\n' "${BITRATE}"
    printf 'TXQUEUELEN=%q\n' "${TXQUEUELEN}"

    for target in "${TARGETS[@]}"; do
      if [[ ! -e "/sys/class/net/${target}" ]]; then
        echo "Missing ${target}; plug both adapters in with the desired current names before install." >&2
        exit 1
      fi

      identity="$(iface_identity "${target}")"
      printf '%s=%q\n' "$(identity_var_name "${target}")" "${identity}"
    done
  } >"${CONFIG_FILE}"
}

install_service() {
  local script_path
  script_path="$(readlink -f "$0")"

  cat >"${SERVICE_FILE}" <<EOF
[Unit]
Description=Robot24 SocketCAN boot setup
Documentation=file://${script_path}
After=systemd-udev-settle.service
Wants=systemd-udev-settle.service
Before=roscore.service

[Service]
Type=oneshot
ExecStart=${script_path} apply
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable robot24-socketcan.service
}

configure_iface() {
  local iface="$1"

  ip link set dev "${iface}" down >/dev/null 2>&1 || true
  ip link set dev "${iface}" type can bitrate "${BITRATE}"
  ip link set dev "${iface}" txqueuelen "${TXQUEUELEN}"
  ip link set dev "${iface}" up
}

rename_to_targets() {
  local target identity source tmp var_name

  for target in "${TARGETS[@]}"; do
    var_name="$(identity_var_name "${target}")"
    identity="${!var_name:-}"
    [[ -n "${identity}" ]] || continue

    source="$(find_iface_by_identity "${identity}" || true)"
    if [[ -z "${source}" ]]; then
      echo "Warning: no interface found for recorded ${target} (${identity})" >&2
      continue
    fi

    if [[ "${source}" != "${target}" ]]; then
      tmp="r24_${target}_tmp"
      ip link set dev "${source}" down >/dev/null 2>&1 || true
      ip link set dev "${source}" name "${tmp}"
    fi
  done

  for target in "${TARGETS[@]}"; do
    var_name="$(identity_var_name "${target}")"
    identity="${!var_name:-}"
    [[ -n "${identity}" ]] || continue

    source="$(find_iface_by_identity "${identity}" || true)"
    if [[ -z "${source}" ]]; then
      continue
    fi

    if [[ "${source}" != "${target}" ]]; then
      ip link set dev "${source}" down >/dev/null 2>&1 || true
      ip link set dev "${source}" name "${target}"
    fi
  done
}

apply_config() {
  local target

  load_config
  rename_to_targets

  for target in "${TARGETS[@]}"; do
    if [[ -e "/sys/class/net/${target}" ]]; then
      configure_iface "${target}"
      echo "Configured ${target}: bitrate=${BITRATE}, txqueuelen=${TXQUEUELEN}, up"
    else
      echo "Warning: ${target} is not present" >&2
    fi
  done
}

show_status() {
  if [[ -r "${CONFIG_FILE}" ]]; then
    echo "Recorded mapping (${CONFIG_FILE}):"
    sed 's/^/  /' "${CONFIG_FILE}"
  else
    echo "No recorded mapping at ${CONFIG_FILE}."
  fi

  echo
  ip -details link show type can || true
}

uninstall_service() {
  systemctl disable --now robot24-socketcan.service >/dev/null 2>&1 || true
  rm -f "${SERVICE_FILE}" "${CONFIG_FILE}"
  systemctl daemon-reload
}

command="${1:-}"
case "${command}" in
  install)
    need_root "$@"
    record_current_mapping
    install_service
    apply_config
    ;;
  apply)
    need_root "$@"
    apply_config
    ;;
  status)
    show_status
    ;;
  uninstall)
    need_root "$@"
    uninstall_service
    ;;
  -h|--help|help|'')
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac